src/Global/GlobalView/Models/ErrorViewModel.cs
namespace GlobalView.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Global/GlobalView/Models/ItemViewModel.cs
namespace GlobalView.Models
{
    public class ItemViewModel
    {
        public List<string>? items { get; set; } 
    }
}

src/Global/GlobalView/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using GlobalView.Models;

namespace GlobalView.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Global/GlobalView/Controllers/ProcurementController.cs
using GlobalView.Models;
using GlobalView.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace GlobalView.Controllers;

[Authorize]
public class ProcurementController : Controller
{
    private readonly ICountryHeadService _countryHeadService;

    public ProcurementController(ICountryHeadService countryHeadService)
    {
        _countryHeadService = countryHeadService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(string button)
    {
        string countryName = button;

        List<string> result = await _countryHeadService.GetProcurementDetailByCountry(countryName);

        ItemViewModel itemView = new ItemViewModel();

        itemView.items = result;

        Console.WriteLine($"\nDisplaying Response from '{countryName} Service' ...");
        foreach (var item in result)
        {
            Console.WriteLine(item);
        }

        Console.WriteLine($"End Response from '{countryName} Service'.");

        //ViewData["result"] = result;
        return View(itemView);
    }

}

src/Global/GlobalView/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h2>Welcome to Service-to-Service Calls Example page</h2>
    <p> Please click <strong>Procurement</strong> link on the top page to start testing</p>
    <p>Learn more about visit <a href="https://learn.microsoft.com/aspnet/core">tutorial section</a> .</p>
</div>

src/Global/GlobalView/Views/Procurement/Index.cshtml
@model ItemViewModel
<h2>
    Procurement Page
</h2>

<div class="card-body">
    @using (Html.BeginForm("Index", "Procurement", FormMethod.Post))
    {
        <p>
            Please click the below button to fetch the all the procurement detail of the country <strong>india</strong>
        </p>
        <p>
            <button class="btn btn-primary" name="button" value="India">India</button>
        </p>

        <p>
            Please click the below button to fetch the all the procurement detail of the country <strong>Bengladesh</strong>
        </p>

        <p>
            <button class="btn btn-secondary" name="button" value="Bengladesh">Bengladesh</button>
        </p>

    }
</div>
<p>Result:</p>
<div>
    @if (Model?.items!=null)
    {
        <ul>
        @foreach (var item in Model.items)
        {
                <li>@item</li>
            
        }
        </ul>
    }
    else
    {
        <div>No item available to display</div>
    }
   

</div>

src/Global/GlobalView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GlobalView</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GlobalView.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GlobalView</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Procurement" asp-action="Index">Procurement</a>
                        </li>
                    </ul>
                </div>
            </div>
            @Html.Partial("_LoginPartial")
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GlobalView - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>